### ISSUE TITLE
O=0g compile option does not work

### ISSUE THREAD

**Issue by ajitmathew** [wuxb45/wormhole#3]
Error Message:
``
clang  -g3 -O0 -rdynamic -march=native -mtune=native -Wall -Wextra -std=gnu11 -pthread -ljemalloc  -o demo1.out demo1.c wh.c  -lrt -lm
/tmp/wh-8ad58a.o: In function `crc32c':
/home/ajit/research/wormhole/wh.c:820: undefined reference to `crc32c_inc'
/tmp/wh-8ad58a.o: In function `wormhole_merge_unsafe':
/home/ajit/research/wormhole/wh.c:3214: undefined reference to `slab_free_unsafe'
/tmp/wh-8ad58a.o: In function `wormhole_clean1':
/home/ajit/research/wormhole/wh.c:3287: undefined reference to `slab_free_unsafe'
/tmp/wh-8ad58a.o: In function `wormhole_alloc_leaf':
/home/ajit/research/wormhole/wh.c:1604: undefined reference to `slab_alloc'
/tmp/wh-8ad58a.o: In function `wormhole_alloc_meta_keyref':
/home/ajit/research/wormhole/wh.c:1622: undefined reference to `slab_alloc_unsafe'
/tmp/wh-8ad58a.o: In function `wormhole_kref_inc_long':
/home/ajit/research/wormhole/wh.c:1709: undefined reference to `crc32c_inc'
/tmp/wh-8ad58a.o: In function `wormhole_prefix_inc_long':
/home/ajit/research/wormhole/wh.c:1701: undefined reference to `crc32c_inc'
/tmp/wh-8ad58a.o: In function `wormhole_merge_ref':
/home/ajit/research/wormhole/wh.c:3126: undefined reference to `slab_free_unsafe'
/tmp/wh-8ad58a.o: In function `wormhole_free_meta':
/home/ajit/research/wormhole/wh.c:1651: undefined reference to `slab_free_unsafe'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile.common:50: demo1.out] Error 1
``
Similar error with gcc compiler.

**Comment by wuxb45** [comment]
Many thanks @ajitmathew . The bug has been fixed.
